<a href="https://colab.research.google.com/github/asiddiqha/ai-workbench/blob/main/Pytouch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. **Installation**

In [1]:
pip install torch torchvision torchaudio

In [2]:
# Import PyTorch library
import torch

# Neural network module
import torch.nn as nn

# Optimizers like Adam, SGD
import torch.optim as optim

# Dataset and DataLoader utilities
from torch.utils.data import Dataset, DataLoader

# NumPy (used for array operations)
import numpy as np

What is this?

* torch → Main PyTorch library.
* torch.nn → Used to build neural networks (layers like Linear, Conv2d, etc.).
* torch.optim → Updates model weights during training.
* Dataset → Represents your dataset.
* DataLoader → Loads data in batches efficiently.
* NumPy → Converts data between NumPy arrays and PyTorch tensors.

In [3]:
# Create a tensor from a Python list

x = torch.tensor([10, 20, 30, 40])
print(x)

tensor([10, 20, 30, 40])


What is it?

A Tensor is the basic data structure in PyTorch.

Python → List

NumPy → ndarray

PyTorch → Tensor

Everything in Deep Learning is stored as a tensor.

2. **Tensor Data Type**

In [ ]:
# Check the data type of a tensor

x = torch.tensor([1, 2, 3])
print(x.dtype)

**3. Tensor Shape**

In [ ]:
# Get the shape (rows, columns) of a tensor

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(x.shape)

**4. Tensor Dimensions**

In [ ]:
# Find the number of dimensions

x = torch.tensor([[1, 2],
                  [3, 4]])
print(x.ndim)

Scalar      → 0D

Vector      → 1D

Matrix      → 2D

Image       → 3D

Video       → 4D

Batch Images→ 4D

**5. Create Different Tensors**

In [ ]:
# Create a tensor filled with zeros

x = torch.zeros((3, 4))
print(x)

In [ ]:
# Create a tensor filled with ones

x = torch.ones((2, 5))
print(x)

In [ ]:
# Create a tensor with random values

x = torch.rand((3, 3))
print(x)

Why?

Neural network weights are initialized randomly before training.

**6. Tensor Arithmetic**

Addition

In [10]:
# Add two tensors element by element

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a + b)

tensor([5, 7, 9])


Subtraction

In [11]:
# Subtract one tensor from another
print(a - b)

tensor([-3, -3, -3])


Multiplication

In [12]:
# Multiply corresponding elements
print(a * b)

tensor([ 4, 10, 18])


Division

In [13]:
# Divide corresponding elements
print(a / b)

tensor([0.2500, 0.4000, 0.5000])


These are the mathematical operations performed throughout neural network training.

**7. Matrix Multiplication**

In [14]:
# Matrix multiplication (not element-wise)

A = torch.tensor([[1, 2],
                  [3, 4]])

B = torch.tensor([[5, 6],
                  [7, 8]])

print(torch.matmul(A, B))

tensor([[19, 22],
        [43, 50]])


Why?

Every ANN layer performs matrix multiplication.

Output = Input × Weight + Bias

**8. Reshape Tensor**

In [15]:
# Change tensor shape without changing data

x = torch.tensor([1, 2, 3, 4, 5, 6])
print(x.reshape(2, 3))

tensor([[1, 2, 3],
        [4, 5, 6]])


Used when preparing data for different neural network layers.

**9. NumPy to Tensor**

In [16]:
# Convert a NumPy array to a PyTorch tensor
import numpy as np
import torch

arr = np.array([10, 20, 30])
tensor = torch.from_numpy(arr)
print(tensor)

tensor([10, 20, 30])


Why?

Most preprocessing uses NumPy or Pandas. PyTorch models require tensors.

**10. Tensor to NumPy**

In [17]:
# Convert a PyTorch tensor back to a NumPy array

x = torch.tensor([5, 10, 15])
print(x.numpy())

[ 5 10 15]


Useful for plotting, exporting, or using NumPy-based libraries.

**11. GPU Support**

In [18]:
# Check whether a CUDA-enabled GPU is available

print(torch.cuda.is_available())

False


Move a tensor to GPU:

In [19]:
# Move tensor to GPU if available

device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([1, 2, 3]).to(device)
print(x)

tensor([1, 2, 3])


Why?

GPUs dramatically speed up deep learning training by performing many calculations in parallel.

**12. Automatic Gradient (Autograd)**

In [20]:
# Compute gradients automatically

x = torch.tensor(5.0, requires_grad=True)
y = x**2
y.backward()
print(x.grad)

tensor(10.)


Why?

Backpropagation relies on gradients. PyTorch computes them automatically, so you don't have to derive them by hand.